/*
389. Find the Difference

    Total Accepted: 21933
    Total Submissions: 44288
    Difficulty: Easy

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter
at a random position. Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

import java.io.*;
import java.util.*;

public class Solution {

    public char findTheDifference(String s, String t) {
        Map<Character, Integer> counters = new HashMap<>();

        for (char c: t.toCharArray())
            counters.put(c, 1+ (counters.containsKey(c) ? counters.get(c) : 0));

        for (char c: s.toCharArray())
        {
            int val = counters.get(c) - 1;
            if (val == 0)
         	counters.remove(c);
            else
                counters.put(c, val);
        }
    
        for (Map.Entry<Character, Integer> e: counters.entrySet())
            return e.getKey();
        return 'a';
    }

    public static void main(String[] args) {
        Solution sol = new Solution();
        String s = "abcd";
        String t = "abcde";
        System.out.println("Result: " + sol.findTheDifference(s, t));
    }
}

